{
    'name':'VK Data Theme',
    'description': 'A theme for VK DATA Denmark.',
    'version':'1.0',
    'author':'NISUS SOLUTIONS - SRI LANKA',

    'data': ['views/layout.xml',
             'views/vkdata_assets.xml',
             'views/vkdata_sn_home.xml',
             'views/vkdata_sn_services.xml',
             'views/vkdata_sn_clients.xml',
             'views/vkdata_sn_partners.xml',
             'views/vkdata_sn_kontaktform.xml',
             'views/vkdata_sn_contact.xml',
             'views/vkdata_sn_footer.xml',
             'views/vkdata_sn_inner_online.xml',
             'views/vkdata_sn_inner_block_a.xml',
             'views/vkdata_sn_inner_block_b.xml',
             'views/vkdata_sn_inner_block_c.xml',
             'views/vkdata_sn_inner_block_d.xml',
             'views/vkdata_sn_inner_kontakt.xml',
             'views/vkdata_sn_team.xml',
             'views/vkdata_sn_header.xml',
             'views/vkdata_sn_bullets_points.xml',
             'views/vkdata_sn_subheader.xml',
             'views/vkdata_sn_pagination.xml',
             #'views/website_template.xml',
          ],
    'category': 'Theme/Creative',
    #'depends': ['website','website_mega_menu_73lines','theme_default','website_animate','website_font_awesome_4_4',],
    'depends': ['website'],
    'installable': True,
    'images':['static/description/icon.png'],
    'favicon':['static/description/favicon.ico'],
    'application': False,
}